// swift-tools-version: 6.0
import Foundation
import PackageDescription

// MARK: - Toolchain quirks
//
// With full Xcode installed, SwiftPM resolves the Swift Testing macro plugin on
// its own. With only the Command Line Tools, `libTestingMacros.dylib` is present
// but never passed to the frontend, so every `@Test` fails to expand. Detecting
// that case here keeps `swift test` working on a machine without Xcode, which is
// the whole point of this project not requiring a paid developer account.
//
// The flag is deliberately *not* added when Xcode is active, because passing the
// plugin twice is an error.

let commandLineToolsRoot = "/Library/Developer/CommandLineTools"

func isCommandLineToolsOnly() -> Bool {
    let fileManager = FileManager.default
    // Xcode ships a Platforms directory; the Command Line Tools do not.
    let hasXcodePlatforms = fileManager.fileExists(
        atPath: "\(commandLineToolsRoot)/Platforms"
    )
    let hasCLTPlugin = fileManager.fileExists(
        atPath: "\(commandLineToolsRoot)/usr/lib/swift/host/plugins/testing/libTestingMacros.dylib"
    )
    return hasCLTPlugin && !hasXcodePlatforms
}

var testSwiftSettings: [SwiftSetting] = [.swiftLanguageMode(.v6)]
if isCommandLineToolsOnly() {
    testSwiftSettings.append(
        .unsafeFlags([
            "-load-plugin-library",
            "\(commandLineToolsRoot)/usr/lib/swift/host/plugins/testing/libTestingMacros.dylib"
        ])
    )
}

let package = Package(
    name: "Biscuit",
    defaultLocalization: "en",
    platforms: [
        .macOS(.v14)
    ],
    products: [
        .executable(name: "Biscuit", targets: ["BiscuitApp"]),
        .executable(name: "biscuit-helper", targets: ["BiscuitHelper"]),
        .library(name: "BiscuitKit", targets: ["BiscuitKit"])
    ],
    targets: [
        // Declarations for the system libarchive. Its header is not in the
        // Command Line Tools SDK, but the library is in the dyld shared cache.
        .target(
            name: "CBiscuitArchive",
            path: "Sources/CBiscuitArchive",
            linkerSettings: [.linkedLibrary("archive"), .linkedLibrary("z")]
        ),
        .target(
            name: "BiscuitKit",
            dependencies: ["CBiscuitArchive"],
            path: "Sources/BiscuitKit",
            // String tables live here. `.process` turns the `.lproj`
            // directories into a resource bundle that `Bundle.module` resolves —
            // including inside the test target, which is why this works without
            // Xcode and without a second copy of every string for tests.
            resources: [.process("Resources")],
            swiftSettings: [
                .swiftLanguageMode(.v6),
                .enableUpcomingFeature("ExistentialAny")
            ]
        ),
        .executableTarget(
            name: "BiscuitHelper",
            dependencies: ["BiscuitKit"],
            path: "Sources/BiscuitHelper",
            swiftSettings: [
                .swiftLanguageMode(.v6)
            ]
        ),
        .executableTarget(
            name: "BiscuitApp",
            dependencies: ["BiscuitKit"],
            path: "Sources/BiscuitApp",
            swiftSettings: [
                .swiftLanguageMode(.v6)
            ]
        ),
        .testTarget(
            name: "BiscuitKitTests",
            dependencies: ["BiscuitKit"],
            path: "Tests/BiscuitKitTests",
            // The sample catalogue is generated by Scripts/build-catalogue.py and
            // decoded in a test, so the generator and the Swift model cannot
            // drift apart unnoticed.
            resources: [.copy("Fixtures")],
            swiftSettings: testSwiftSettings
        )
    ]
)
